Nom : POULI

Prénom : Epiphane-Gédéon

Classe : Master 1 session mars 2026

# Selenium

In [1]:
!pip install google-colab-selenium

Collecting google-colab-selenium
  Downloading google_colab_selenium-1.0.18-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: notebook>=6.5.7 in /usr/local/lib/python3.12/dist-packages (from google-colab-selenium) (6.5.7)
Collecting selenium (from google-colab-selenium)
  Downloading selenium-4.47.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (3.1.6)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (6.5.7)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (26.2.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (25.1.0)
Requirement already satisfied: traitlets>=4.2.1 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (5.7.1)
Requirement already satisfied: jupyter-core>=4.6.1 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (5.9.1)
Requirement already satisfied: jupyter-client<8,>=5.3.4 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (7.4.9)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (0.2.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (5.10.4)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (7.17.1)
Requirement already satisfied: nest-asyncio>=1.5 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (1.6.0)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (6.17.1)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (0.25.0)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from notebook>=6.5.7->google-colab-selenium) (1.3.3)
Requirement already satisfied: certifi>=2026.2.25 in /usr/local/lib/python3.12/dist-packages (from selenium->google-colab-selenium) (2026.6.17)
Collecting trio<1.0,>=0.31.0 (from selenium->google-colab-selenium)
  Downloading trio-0.34.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket<1.0,>=0.12.2 (from selenium->google-colab-selenium)
  Downloading trio_websocket-0.12.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in /usr/local/lib/python3.12/dist-packages (from selenium->google-colab-selenium) (4.16.0)
Collecting urllib3<3.0,>=2.6.3 (from urllib3[socks]<3.0,>=2.6.3->selenium->google-colab-selenium)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from selenium->google-colab-selenium) (1.9.0)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client<8,>=5.3.4->notebook>=6.5.7->google-colab-selenium) (0.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from jupyter-client<8,>=5.3.4->notebook>=6.5.7->google-colab-selenium) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core>=4.6.1->notebook>=6.5.7->google-colab-selenium) (4.10.0)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.12/dist-packages (from nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (0.2.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (6.4.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (3.0.3)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (3.3.3)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (0.10.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (26.2)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (1.5.1)
Requirement already satisfied: pygments>=2.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (2.20.0)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->notebook>=6.5.7->google-colab-selenium) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->notebook>=6.5.7->google-colab-selenium) (4.26.0)
Requirement already satisfied: ptyprocess in /usr/local/lib/python3.12/dist-packages (from terminado>=0.8.3->notebook>=6.5.7->google-colab-selenium) (0.7.0)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium->google-colab-selenium) (26.1.0)
Collecting sortedcontainers (from trio<1.0,>=0.31.0->selenium->google-colab-selenium)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium->google-colab-selenium) (3.18)
Collecting outcome (from trio<1.0,>=0.31.0->selenium->google-colab-selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from trio<1.0,>=0.31.0->selenium->google-colab-selenium) (1.3.1)
Collecting wsproto>=0.14 (from trio-websocket<1.0,>=0.12.2->selenium->google-colab-selenium)
  Downloading wsproto-1.3.2-py3-none-any.whl.metadata (5.2 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from urllib3[socks]<3.0,>=2.6.3->selenium->google-colab-selenium) (1.7.1)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/dist-packages (from argon2-cffi->notebook>=6.5.7->google-colab-selenium) (25.1.0)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel->notebook>=6.5.7->google-colab-selenium) (1.8.15)
Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel->notebook>=6.5.7->google-colab-selenium) (7.34.0)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel->notebook>=6.5.7->google-colab-selenium) (0.2.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel->notebook>=6.5.7->google-colab-selenium) (5.9.5)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (0.5.1)
Requirement already satisfied: tinycss2>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (1.5.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->notebook>=6.5.7->google-colab-selenium) (75.2.0)
Collecting jedi>=0.16 (from ipython>=7.23.1->ipykernel->notebook>=6.5.7->google-colab-selenium)
  Downloading jedi-0.20.0-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->notebook>=6.5.7->google-colab-selenium) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->notebook>=6.5.7->google-colab-selenium) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->notebook>=6.5.7->google-colab-selenium) (3.0.52)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->notebook>=6.5.7->google-colab-selenium) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->notebook>=6.5.7->google-colab-selenium) (4.9.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook>=6.5.7->google-colab-selenium) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook>=6.5.7->google-colab-selenium) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook>=6.5.7->google-colab-selenium) (2026.6.3)
Requirement already satisfied: jupyter-server<3,>=1.8 in /usr/local/lib/python3.12/dist-packages (from notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (2.20.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->jupyter-client<8,>=5.3.4->notebook>=6.5.7->google-colab-selenium) (1.17.0)
Requirement already satisfied: h11<1,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium->google-colab-selenium) (0.16.0)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=6.5.7->google-colab-selenium) (2.1.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->nbconvert>=5->notebook>=6.5.7->google-colab-selenium) (2.8.4)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=6.5.7->google-colab-selenium) (3.0)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->notebook>=6.5.7->google-colab-selenium) (0.8.7)
Requirement already satisfied: anyio>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (4.14.2)
Requirement already satisfied: jupyter-events>=0.11.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (0.12.1)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (0.5.4)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.23.1->ipykernel->notebook>=6.5.7->google-colab-selenium) (0.8.2)
Requirement already satisfied: python-json-logger>=2.0.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (4.1.0)
Requirement already satisfied: pyyaml>=5.3 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (6.0.3)
Requirement already satisfied: rfc3339-validator in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (0.1.1)
Requirement already satisfied: fqdn in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (1.5.1)
Requirement already satisfied: isoduration in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (3.1.1)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (1.1.0)
Requirement already satisfied: uri-template in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (25.10.0)
Requirement already satisfied: lark>=1.2.2 in /usr/local/lib/python3.12/dist-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (1.3.1)
Requirement already satisfied: arrow>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (1.4.0)
Requirement already satisfied: tzdata in /usr/local/lib/python3.12/dist-packages (from arrow>=0.15.0->isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=6.5.7->google-colab-selenium) (2026.3)
Downloading google_colab_selenium-1.0.18-py3-none-any.whl (10 kB)
Downloading selenium-4.47.0-py3-none-any.whl (9.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 62.7 MB/s eta 0:00:00
Downloading trio-0.34.0-py3-none-any.whl (511 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.8/511.8 kB 29.2 MB/s eta 0:00:00
Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.1/131.1 kB 9.1 MB/s eta 0:00:00
Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Downloading jedi-0.20.0-py2.py3-none-any.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 85.5 MB/s eta 0:00:00
Installing collected packages: sortedcontainers, wsproto, urllib3, outcome, jedi, trio, trio-websocket, selenium, google-colab-selenium
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.5.0
    Uninstalling urllib3-2.5.0:
      Successfully uninstalled urllib3-2.5.0
Successfully installed google-colab-selenium-1.0.18 jedi-0.20.0 outcome-1.3.0.post0 selenium-4.47.0 sortedcontainers-2.4.0 trio-0.34.0 trio-websocket-0.12.2 urllib3-2.7.0 wsproto-1.3.2

In [2]:
# importer packages
import pandas as pd
from selenium.webdriver.common.by import By
import google_colab_selenium as gs
import time

In [6]:
# Lancer le navigateur
driver = gs.Chrome()

## Books To scrap

In [7]:
df_test = pd.DataFrame()
limit = 0
i = 1
url = f'https://books.toscrape.com/catalogue/page-{i}.html'
driver.get(url)
containers = driver.find_elements(By.CSS_SELECTOR, 'article.product_pod')



while len(containers) > 0:

  if i > limit and limit > 0 :
    break

  url = f'https://books.toscrape.com/catalogue/page-{i}.html'
  driver.get(url)

  containers = driver.find_elements(By.CSS_SELECTOR, 'article.product_pod')

  book_urls = []
  data_cont = []
  for container in containers:
    book_urls.append(container.find_element(By.CSS_SELECTOR, 'a').get_attribute('href'))
    stock = container.find_element(By.CSS_SELECTOR, 'p.instock.availability').text

  for book_url in book_urls:
    driver.get(book_url)

    try :
      dic={
            'title' : driver.find_element(By.CSS_SELECTOR, 'h1').text,
            'price' : driver.find_element(By.CSS_SELECTOR, 'p.price_color').text,
            'availability' : stock,
            'number_of_products' : driver.find_element(By.CSS_SELECTOR, 'table.table.table-striped tr:nth-child(6) td:nth-child(2)').text,
            'rating' : driver.find_element(By.CSS_SELECTOR, 'p.star-rating').get_attribute('class'),
            'number_of_reviews' : driver.find_element(By.CSS_SELECTOR, 'table.table.table-striped tr:nth-child(7) td:nth-child(2)').text,
            'description' : driver.find_element(By.CSS_SELECTOR, 'article.product_page > p:nth-of-type(1)').text,
            'product_type' : driver.find_element(By.CSS_SELECTOR, 'table.table.table-striped tr:nth-child(2) td:nth-child(2)').text,
            'tax' : driver.find_element(By.CSS_SELECTOR, 'table.table.table-striped tr:nth-child(5) td:nth-child(2)').text
        }
      data_cont.append(dic)

    except :
      pass
  df = pd.DataFrame(data_cont)
  df_test = pd.concat([df_test, df], axis = 0).reset_index(drop = True)


  i += 1

In [8]:
df_test.head()

,title,price,availability,number_of_products,rating,number_of_reviews,description,product_type,tax
0,A Light in the Attic,£51.77,In stock,In stock (22 available),star-rating Three,0,It's hard to imagine a world without A Light i...,Books,£0.00
1,Tipping the Velvet,£53.74,In stock,In stock (20 available),star-rating One,0,"""Erotic and absorbing...Written with starling ...",Books,£0.00
2,Soumission,£50.10,In stock,In stock (20 available),star-rating One,0,"Dans une France assez proche de la nôtre, un h...",Books,£0.00
3,Sharp Objects,£47.82,In stock,In stock (20 available),star-rating Four,0,"WICKED above her hipbone, GIRL across her hear...",Books,£0.00
4,Sapiens: A Brief History of Humankind,£54.23,In stock,In stock (20 available),star-rating Five,0,From a renowned historian comes a groundbreaki...,Books,£0.00

In [9]:
df_test.shape

(998, 9)

In [10]:
df_test.describe()

,title,price,availability,number_of_products,rating,number_of_reviews,description,product_type,tax
count,998,998,998,998,998,998,998,998,998
unique,997,902,1,21,5,1,998,1,1
top,The Star-Touched Queen,£44.18,In stock,In stock (3 available),star-rating One,0,"Around the World, continent by continent, here...",Books,£0.00
freq,2,3,998,196,225,998,1,998,998

In [11]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 998 entries, 0 to 997
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               998 non-null    object
 1   price               998 non-null    object
 2   availability        998 non-null    object
 3   number_of_products  998 non-null    object
 4   rating              998 non-null    object
 5   number_of_reviews   998 non-null    object
 6   description         998 non-null    object
 7   product_type        998 non-null    object
 8   tax                 998 non-null    object
dtypes: object(9)
memory usage: 70.3+ KB

In [12]:
df_test.isnull().sum()

title                 0
price                 0
availability          0
number_of_products    0
rating                0
number_of_reviews     0
description           0
product_type          0
tax                   0
dtype: int64

In [13]:
df_test.isna().sum()

title                 0
price                 0
availability          0
number_of_products    0
rating                0
number_of_reviews     0
description           0
product_type          0
tax                   0
dtype: int64

In [14]:
df_test[['price', 'tax']] = df_test[['price', 'tax']].replace('£', '', regex=True).astype(float)
df_test.head()

,title,price,availability,number_of_products,rating,number_of_reviews,description,product_type,tax
0,A Light in the Attic,51.77,In stock,In stock (22 available),star-rating Three,0,It's hard to imagine a world without A Light i...,Books,0.0
1,Tipping the Velvet,53.74,In stock,In stock (20 available),star-rating One,0,"""Erotic and absorbing...Written with starling ...",Books,0.0
2,Soumission,50.10,In stock,In stock (20 available),star-rating One,0,"Dans une France assez proche de la nôtre, un h...",Books,0.0
3,Sharp Objects,47.82,In stock,In stock (20 available),star-rating Four,0,"WICKED above her hipbone, GIRL across her hear...",Books,0.0
4,Sapiens: A Brief History of Humankind,54.23,In stock,In stock (20 available),star-rating Five,0,From a renowned historian comes a groundbreaki...,Books,0.0

In [15]:
df_test['number_of_products'] = df_test['number_of_products'].str.replace('In stock (', '').str.replace(' available)', '').astype(int)
df_test['rating'] = df_test['rating'].str.replace('star-rating ', '')
df_test.head()

,title,price,availability,number_of_products,rating,number_of_reviews,description,product_type,tax
0,A Light in the Attic,51.77,In stock,22,Three,0,It's hard to imagine a world without A Light i...,Books,0.0
1,Tipping the Velvet,53.74,In stock,20,One,0,"""Erotic and absorbing...Written with starling ...",Books,0.0
2,Soumission,50.10,In stock,20,One,0,"Dans une France assez proche de la nôtre, un h...",Books,0.0
3,Sharp Objects,47.82,In stock,20,Four,0,"WICKED above her hipbone, GIRL across her hear...",Books,0.0
4,Sapiens: A Brief History of Humankind,54.23,In stock,20,Five,0,From a renowned historian comes a groundbreaki...,Books,0.0

In [16]:
correspondance = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

df_test['rating'] = df_test['rating'].map(correspondance)

df_test.head()

,title,price,availability,number_of_products,rating,number_of_reviews,description,product_type,tax
0,A Light in the Attic,51.77,In stock,22,3,0,It's hard to imagine a world without A Light i...,Books,0.0
1,Tipping the Velvet,53.74,In stock,20,1,0,"""Erotic and absorbing...Written with starling ...",Books,0.0
2,Soumission,50.10,In stock,20,1,0,"Dans une France assez proche de la nôtre, un h...",Books,0.0
3,Sharp Objects,47.82,In stock,20,4,0,"WICKED above her hipbone, GIRL across her hear...",Books,0.0
4,Sapiens: A Brief History of Humankind,54.23,In stock,20,5,0,From a renowned historian comes a groundbreaki...,Books,0.0

In [17]:
df_test.shape

(998, 9)

In [18]:
df_test.describe()

            price  number_of_products      rating    tax
count  998.000000          998.000000  998.000000  998.0
mean    35.052926            8.586172    2.924850    0.0
std     14.446311            5.651540    1.435111    0.0
min     10.000000            1.000000    1.000000    0.0
25%     22.102500            3.000000    2.000000    0.0
50%     35.980000            7.000000    3.000000    0.0
75%     47.407500           14.000000    4.000000    0.0
max     59.990000           22.000000    5.000000    0.0

In [19]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 998 entries, 0 to 997
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   title               998 non-null    object
 1   price               998 non-null    float64
 2   availability        998 non-null    object
 3   number_of_products  998 non-null    int64
 4   rating              998 non-null    int64
 5   number_of_reviews   998 non-null    object
 6   description         998 non-null    object
 7   product_type        998 non-null    object
 8   tax                 998 non-null    float64
dtypes: float64(2), int64(2), object(5)
memory usage: 70.3+ KB

In [20]:
df_test.isnull().sum()

title                 0
price                 0
availability          0
number_of_products    0
rating                0
number_of_reviews     0
description           0
product_type          0
tax                   0
dtype: int64

In [21]:
df_test.isna().sum()

title                 0
price                 0
availability          0
number_of_products    0
rating                0
number_of_reviews     0
description           0
product_type          0
tax                   0
dtype: int64

## Gaaraas.com

In [22]:
url = f'https://www.gaaraas.com/fr/users/dakar-auto?page=1'
driver.get(url)

containers = driver.find_elements(By.CSS_SELECTOR, 'a.common-ad-card')

In [23]:
containers[0].find_element(By.CSS_SELECTOR, '.specification-section h4').text

'2008 Nissan Murano'

In [24]:
import re
df_gaaraas = pd.DataFrame()

limit = 0
i = 1
url = f'https://www.gaaraas.com/fr/users/dakar-auto?page={i}'
driver.get(url)
containers = driver.find_elements(By.CSS_SELECTOR, 'a.common-ad-card')

while len(containers) > 0 :

  if i > limit and limit > 0 :
    break

  url = f'https://www.gaaraas.com/fr/users/dakar-auto?page={i}'
  driver.get(url)

  containers = driver.find_elements(By.CSS_SELECTOR, 'a.common-ad-card')


  data_cont = []
  for container in containers:
    car_info_text = container.find_element(By.CSS_SELECTOR, '.ad-specification .specification-section h4').text

    match = re.match(r'^(\d{4})\s+([^\s]+)(?:\s+(.*))?$', car_info_text)

    if match:
        year = match.group(1)
        brand = match.group(2)
        model = match.group(3) if match.group(3) is not None else ""
    else:
        year = car_info_text
        brand= car_info_text
        model = car_info_text

    try :
      dic={
            'brand' : brand,
            'model' : model,
            'year' : year,
            'price' : driver.find_element(By.CSS_SELECTOR, '.ad-vehicle-price .price-wrap .price').text,
            'kilometers' : driver.find_element(By.CSS_SELECTOR, '.ad-vehicle-mileage .title .value').text,
            'gear_box' : driver.find_element(By.CSS_SELECTOR, '.ad-vehicle-engine .transmission').text,
            'seling_region' : driver.find_element(By.CSS_SELECTOR, '.ad-specification .specification-section .location').text,
      }
      data_cont.append(dic)
    except:
      pass
  df = pd.DataFrame(data_cont)
  df_gaaraas = pd.concat([df_gaaraas, df], axis = 0).reset_index(drop = True)

  i += 1

In [25]:
df_gaaraas.shape

(245, 7)

In [26]:
df_gaaraas.describe()

          brand model  year      price  kilometers  gear_box seling_region
count       245   245   245        245         245       245           245
unique       29    97    17         11          10         2             1
top     Peugeot   307  2007  2 700 000  160 000 KM  Manuelle         Dakar
freq         65    26    52         40          40       205           245

In [27]:
df_gaaraas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 245 entries, 0 to 244
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   brand          245 non-null    object
 1   model          245 non-null    object
 2   year           245 non-null    object
 3   price          245 non-null    object
 4   kilometers     245 non-null    object
 5   gear_box       245 non-null    object
 6   seling_region  245 non-null    object
dtypes: object(7)
memory usage: 13.5+ KB

In [28]:
df_gaaraas.isnull().sum()

brand            0
model            0
year             0
price            0
kilometers       0
gear_box         0
seling_region    0
dtype: int64

In [29]:
df_gaaraas.isna().sum()

brand            0
model            0
year             0
price            0
kilometers       0
gear_box         0
seling_region    0
dtype: int64

In [30]:
df_gaaraas['price']= df_gaaraas['price'].str.replace(' ', '').astype(int)
df_gaaraas['kilometers']= df_gaaraas['kilometers'].str.replace('KM','').str.replace(' ', '').astype(int)
df_gaaraas['year'] = pd.to_numeric(df_gaaraas['year'], errors='coerce').astype(pd.Int64Dtype())
df_gaaraas.head(10)

        brand     model  year    price  kilometers     gear_box seling_region
0      Nissan    Murano  2008  3200000      115305  Automatique         Dakar
1        Ford    Escort  2007  3200000      115305  Automatique         Dakar
2      Nissan   Qashqai  2014  3200000      115305  Automatique         Dakar
3       Mazda         6  2010  3200000      115305  Automatique         Dakar
4     Peugeot       307  2007  3200000      115305  Automatique         Dakar
5     Citroen        C3  2008  3200000      115305  Automatique         Dakar
6  Volkswagen      Golf  2003  3200000      115305  Automatique         Dakar
7     Hyundai    Tucson  2008  3200000      115305  Automatique         Dakar
8      Nissan    Murano  2011  3200000      115305  Automatique         Dakar
9     Citroen  Berlingo  2008  3200000      115305  Automatique         Dakar

In [31]:
df_gaaraas.head(20)

,brand,model,year,price,kilometers,gear_box,seling_region
0,Nissan,Murano,2008,3200000,115305,Automatique,Dakar
1,Ford,Escort,2007,3200000,115305,Automatique,Dakar
2,Nissan,Qashqai,2014,3200000,115305,Automatique,Dakar
3,Mazda,6,2010,3200000,115305,Automatique,Dakar
4,Peugeot,307,2007,3200000,115305,Automatique,Dakar
5,Citroen,C3,2008,3200000,115305,Automatique,Dakar
6,Volkswagen,Golf,2003,3200000,115305,Automatique,Dakar
7,Hyundai,Tucson,2008,3200000,115305,Automatique,Dakar
8,Nissan,Murano,2011,3200000,115305,Automatique,Dakar
9,Citroen,Berlingo,2008,3200000,115305,Automatique,Dakar
10,Citroen C3,Citroen C3,<NA>,3200000,115305,Automatique,Dakar
11,Ford,Edge,2011,3200000,115305,Automatique,Dakar
12,Land,Rover Range Rover Sport,2008,3200000,115305,Automatique,Dakar
13,Toyota,Auris,2005,3200000,115305,Automatique,Dakar
14,Mitsubishi,L200,2006,3200000,115305,Automatique,Dakar
15,Mercedes‒Benz,190,2004,3200000,115305,Automatique,Dakar
16,Peugeot,308,2012,3200000,115305,Automatique,Dakar
17,Renault,Scenic,2009,3200000,115305,Automatique,Dakar
18,Nissan,Altima,2014,3200000,115305,Automatique,Dakar
19,Peugeot,605,2004,3200000,115305,Automatique,Dakar

In [32]:
df_gaaraas.isnull().sum()

brand            0
model            0
year             1
price            0
kilometers       0
gear_box         0
seling_region    0
dtype: int64

In [33]:
df_gaaraas.dropna(inplace=True)
df_gaaraas.isnull().sum()

brand            0
model            0
year             0
price            0
kilometers       0
gear_box         0
seling_region    0
dtype: int64

In [34]:
df_gaaraas.to_csv('gaaraas_clean.csv', index = False)
df_test.to_csv('books_to_scrap_clean.csv', index = False)